
################################################################################
[register.plain_dummy_reg]

mode = "r_w"
description = "A plain dummy register."
default_value = 1337

[register.plain_dummy_reg.bits]

inject = ""


################################################################################
[register_array.dummy_regs]

array_length = 3

[register_array.dummy_regs.register.configuration]

mode= "r_w"
description = "The first register in the array."
default_value = 42

[register_array.dummy_regs.register.configuration.bits]

enable = ""
disable = ""

[register_array.dummy_regs.register.settings]

description = "The second register in the array."
mode= "r"

