# Instructions here: https://docs.gitlab.com/ee/ci/yaml/
# Linter here: https://gitlab.com/truestream/tsfpga/-/ci/lint

# Use docker image from ghdl project
# Available at https://hub.docker.com/r/ghdl/ext/
# Configured at https://github.com/ghdl/docker/tree/master/dockerfiles
# Note that docker image can also be set on a stage/job basis
image: ghdl/ext:vunit


before_script:
  - apt-get update -qq > /dev/null
  - apt-get install -y -qq git > /dev/null
  - python3 --version
  - export PYTHONPATH=$(pwd)/tsfpga

pytest:
  script:
    - python3 -m pip install pytest pylint pycodestyle > /dev/null
    - python3 -m pylint --version
    - python3 -m pycodestyle --version
    - python3 -m pytest -v --ignore=tsfpga/test/vivado/ tsfpga/

simulate:
  script:
    - ghdl --version
    - python3 tsfpga/examples/simulate.py --num-threads 4 --ip-skip
