# Instructions here: https://docs.gitlab.com/ee/ci/yaml/
# Linter here: https://gitlab.com/truestream/tsfpga/-/ci/lint

stages:
  - test
  - deploy

default:
  # docker image with python3 and apt-get
  image: python:3.8-slim-buster
  before_script:
    - python3 --version
    - export PYTHONPATH=$(pwd)/tsfpga

pytest:
  stage: test
  script:
    - apt-get update -qq > /dev/null
    - apt-get install -y -qq git g++ > /dev/null
    - python3 -m pip install pytest pylint pycodestyle > /dev/null
    - python3 -m pylint --version
    - python3 -m pycodestyle --version
    - python3 -m pytest -v --ignore=tsfpga/test/vivado/ tsfpga/

simulate:
  stage: test
  # Use docker image from ghdl project
  # Available at https://hub.docker.com/r/ghdl/ext/
  # Configured at https://github.com/ghdl/docker/tree/master/dockerfiles
  image: ghdl/ext:ls-vunit
  script:
    - python3 -m pip install toml > /dev/null
    - ghdl --version
    - python3 examples/simulate.py --num-threads 4 --vivado-skip

deploy_pypi:
  stage: deploy
  only:
    - tags
  except:
    - schedules
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $PYPI_API_TOKEN
  script:
    - apt-get update -qq > /dev/null
    - apt-get install -y -qq git > /dev/null
    - python3 -m pip install twine > /dev/null
    - python3 tools/verify_release.py
    - python3 setup.py sdist
    - python3 -m twine upload dist/*
